image: gcc

build:
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y cmake
    - git clone https://github.com/quandangv/linked_nodes 
    - cd linked_nodes
    - ./build.sh -A
    - cd ..
  script:
    - make
    - make install
  #artifacts:
  #  paths:

